#cloud-config
hostname: localhost
fqdn: localhost.localdomain
manage_etc_hosts: true
users:
  - name: user
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: false
ssh_pwauth: True
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
runcmd:
  - systemctl enable --now qemu-guest-agent
  - sed -i -E 's/^#?PasswordAuthentication\s+.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - touch /var/log/cloud-init-allow-ssh.done
final_message: "The system is finally up, after $UPTIME seconds"
